### ISSUE TITLE
Chrome blocking downloads of releases

### ISSUE THREAD

**Issue by Hughp135** [cbuchner1/driver_leap#14]
Both v8 and v3 releases are blocked by chrome, flagged as being 'malicious'...

[Screenshot](http://imgur.com/dhJHqer)

**Comment by Hughp135** [comment]
Noticed this issue was closed before already

**Comment by cbuchner1** [comment]
A lot of browsers seem to err on the side of caution, when executables are
downloaded that have not been seen (much) before.
The same applies to a lot of virus scanners who use heuristics to determine
the probability of malicious behavior.

I do provide the source code as well, for people who know how to use
development tools.

2016-08-09 13:22 GMT+02:00 Hughp135 notifications@github.com:
