### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by nntb** [cbuchner1/driver_leap#2]
Windows 10
DK2 
Leapmotion

installed prerequsits not sure if i had to install when steam vr was not running so closed steam vr and reinstalled tried installing all in order 1-4 after uninstalling just 4 that i had orignally installed. using latest orin drivers 

https://youtu.be/R-lBBqB1SXc?t=221 here is a video of my trying to get it to run. its kind of frustrating

**Comment by cbuchner1** [comment]
Try alpha version #3, as #4 has a known bug with spaces in the path name to the steam install directory. Currently vacationing with no access to a PC, sorry.

Von meinem iPhone gesendet

**Comment by VRKommando** [comment]
Same issue here, I have tried everything reinstalling steam multiple times in different locations, as well as steamvr, and have tried all 4 releases, at one point I got it to work on release #2 but then I broke it
and never was able to replicate it, when I run the script via prompt, it says it has not detected the steam directory 

But anyways enjoy your vacation man dont worry about us :)

**Comment by VRKommando** [comment]
Same issue here, I have tried everything reinstalling steam multiple times in different locations, as well as steamvr, and have tried all 4 releases, at one point I got it to work on release #2 but then I broke it
and never was able to replicate it, when I run the script via prompt, it says it has not detected the steam directory 

But anyways have a nice vacation man dont worry about us :)

**Comment by wostg** [comment]
I've tried to download the last few releases. Chrome and Adaware have both deleted/quarantined the zip and installed driver. Maybe its affecting others as well.

**Comment by nntb** [comment]
in my orignal post i mentioned i installed and tryed 1 - 4 in order. so i tried 1 then i tried 2 then 3 then 4 but initaly i tried 4 
i did this with steam vr normal, steam vr beta, installing VIVE drivers *(eventhough i dont have a vive) 
i dont have a hydra do i need hydra drivers? 

its sad these drivers just dont seem to work for me at all.

**Comment by nntb** [comment]
when i say not working i mean ill start steam vr and there is no indication of motion controllers detected. 

leap motion 
firmware version is 1.7.0 
software version 3.1.2+40841

**Comment by comanderxv** [comment]
In my case windows 10 had missing the "32bi Visual C++ 2015 Update 2 redistributables" . 64Bit was already there. You should check this first in apps section of win10.

**Comment by BenReierson** [comment]
Alpha 4 didn't work for me, Alpha 3 did. I'm not sure why though, there aren't spaces in my steam dirs. Just D:\Valve\Steam\ and D:\Valve\Steam\steamapps\common\SteamVR

**Comment by thomasvt1** [comment]
Tried alpha 5. But still doesn't work for me - Alpha 3 is the lastest version that worked for me.

**Comment by wostg** [comment]
Same - vrpathreg for 4 and 5 displayed the install folder but not the
/leap/ folder inside, if that helps.

**Comment by nntb** [comment]
got mine to work i had to edit the register driver cmd file 

i changed %steamdir% to my dir for steam that had the folder of openvr steamvr for me it was E:\steamapps\

after running it worked. i tried running a game but the framrate is awfull. (my fault for having a gtx 670 

https://www.twitch.tv/nntb/v/70363829 here you can see me trying to set it up (8 mins in i got the hands working but the game crashes as i load it) i am sure i just need a better system. but yeah got it up and running! thanks

**Comment by nntb** [comment]
i forgot to close my issue... sorry i am new to this.
