### ISSUE TITLE
Windows Defender won't let me download it. Claims RunDas.b Trojan. 

### ISSUE THREAD

**Issue by mrdanjohnson** [cbuchner1/driver_leap#25]
When I try to download the Alpha 3 Bin or Source code, Defender deletes it because it detects the RunDas.b virus.

**Comment by ajayyy** [comment]
Click the releases tab.

**Comment by ajayyy** [comment]
It has the installer

**Comment by mrdanjohnson** [comment]
Alpha 8 installed, but didn't detect controlers. I tried the Alpha3, and get the virus warning.

**Comment by ajayyy** [comment]
Hmm, do you have the prerequisites installed, are you sure the leap is working? Have you tried restarting?

**Comment by mrdanjohnson** [comment]
My leap is working fine with it's vr demos. I have not tried restarting. I had it working like 10 months under an earlier alpha. I will try to restart. Just wondering why defender is detecting a virus in alpha3. It seems alpha3 is working better for people.

**Comment by ajayyy** [comment]
Oh I see, I just saw you said the source code said it was the virus. Is it the installer too?

**Comment by mrdanjohnson** [comment]
Yes. Both the Binary and Source gets detected by defender as RasDas.b Trojan. I don't want my computer to be doing someone else's mining.

**Comment by ajayyy** [comment]
Weird
