### ISSUE TITLE
left-handed in SteamVR

### ISSUE THREAD

**Issue by maso27** [cbuchner1/driver_leap#4]
I'm not sure if this is related to the driver or not, but when I'm in SteamVR, my controllers appear to be set up left-handed.  I have to point and click everything with my left hand, not my right.

Something that may contribute to this is that my Leap Motion is installed upside-down to ease with cable routing.  Could it be perceiving the controllers as in the opposite hands?

Or if this isn't related to the driver, does anyone know how to switch the handed-ness?

**Comment by VRKommando** [comment]
In some apps by default require the leap motion to be in the position where its facing your screen and the usb cable coming out of the left side

**Comment by maso27** [comment]
This is in the main SteamVR window.  When I do "T" and bring up the menus, the pointer laser comes out of the left hand and I have to pull the left trigger.

I tried unmounting my Leap and flipping it over, but the left-handedness remained.
I've tried going through the settings, but it's flaky enough to control anyway that doing it left-handed is teeth-grittingly hard.  But I couldn't find anything that would change it.

**Comment by maso27** [comment]
Figured it out.

It comes down to how you do the "T".  If your right hand makes the cross bar on top, the menu comes up left-handed.  If your left hand makes the cross bar on top, the menu comes up right-handed.

Apparently I'm a left-handed T-er.

**Comment by wissper** [comment]
I had that issue before, and loading up the steam visualizer and checking reverse orientation resolved it
