### ISSUE TITLE
Chrome reporting the zip files as malicious

### ISSUE THREAD

**Issue by ChuckLeone** [cbuchner1/driver_leap#5]
I'm on Windows 10 x64 using Chrome Version 51.0.2704.84 m
- chrome is reporting the zip version of the alpha #8 installer as malicious and blocks the file from downloading

**Comment by VRKommando** [comment]
I get that a lot but I just tell it gimme anyways :)

**Comment by ChuckLeone** [comment]
I figured as much but i didn't get that message from previous installers so I figured it was worth mentioning.

**Comment by Tyrminaotr** [comment]
Forks fine for me! :)
Win10 / RiftCat 0.9 / S6 Edge +

Pozdrawiam gorąco,

Ziemowit Brodzikowski
www.magnus-organy.eu
www.facebook.com/magnusorgan
tel. + 48 502 656 252

2016-06-11 19:33 GMT+02:00 Chuck Leone notifications@github.com:
